source 'https://rubygems.org'

gem 'appium_capybara'
gem 'appium_lib'
gem 'capybara'
gem 'cucumber'
gem 'dotenv'
gem 'ffaker'
gem 'require_all'
gem 'rest-client'
gem 'rspec-expectations'
gem 'securerandom'
gem 'selenium-webdriver'
gem 'site_prism'

